---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Ensure software-properties-common is installed
  apt:
    name: software-properties-common
    state: present
  become: yes

- name: Enable universe repository
  command: add-apt-repository -y universe
  args:
    creates: /etc/apt/sources.list.d/ubuntu.sources
  become: yes
  ignore_errors: yes   # in case repo is already enabled

- name: Update apt cache after enabling universe
  apt:
    update_cache: yes
  become: yes

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ packages_list }}"
  when: packages_list | length > 0
  become: yes
